### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by ndmitchell** [GaloisInc/pure-zlib#2]
I don't want anything too precise, but just taking a random gzip'd tarball (e.g. one of the many on Hackage), what's the performance difference between this library and the Haskell zlib binding? Just phrases like "about the same speed" or "64x slower" would let people make the choice in a more informed way.

**Comment by acw** [comment]
I'm just commenting here to note that:
  * I am totally interested in this question, and will answer it.
  * This question caught me mid-refactor.
  * Travel sucks.
  * Apparently I can't successfully roll my own monads any more.

**Comment by acw** [comment]
Well, I finally have numbers. Which, sadly, are not great; this pure version is a couple orders of magnitude slower than the C version.

**Comment by ndmitchell** [comment]
Thanks for the info - very useful to know - and great that it's in the readme now.
